### ISSUE TITLE
pxd 创建标准集群，提供的 admin 账户，无授权权限

### ISSUE THREAD

**Issue by zerolincku** [polardb/polardbx-sql#230]
## 配置文件
```yaml
version: v1
type: polardbx
cluster:
  name: pxc_test
  dn:
    image: polardbx-opensource-registry.cn-beijing.cr.aliyuncs.com/polardbx/polardbx-engine:v2.4.1_8.4.19
    replica: 1
    nodes:
      - host_group: [127.0.0.1,127.0.0.1,127.0.0.1]
    resources:
      mem_limit: 2G
```

## 安装

pxd create -file polarx.yaml

Processing  [##################------------------]   50%    create dn
Processing  [#################################---]   92%    wait PolarDB-X ready
Processing  [####################################]  100%

PolarDB-X cluster create successfully, you can try it out now.
Connect PolarDB-X using the following command:

    mysql -h127.0.0.1 -P17825 -uadmin -prafpsDOQ

## 结果
无法授权

```bash
(venv) [polarx@rocky ~]$ mysql -h127.0.0.1 -P17825 -uadmin -prafpsDOQ
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 28
Server version: 8.0.32-X-Cluster-8.4.19-20241111 Source distribution

Copyright (c) 2000, 2024, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

No entry for terminal type "xterm-ghostty";
using dumb terminal settings.
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> GRANT SELECT on sys.* to 'proxysql_monitor'@'%';
ERROR 1044 (42000): Access denied for user 'admin'@'%' to database 'sys'
mysql> GRANT SELECT on *.* to 'proxysql_monitor'@'%';
ERROR 1045 (28000): Access denied for user 'admin'@'%' (using password: YES)
mysql>
```

## 问题
1. 请问使用 pxd 安装标准集群如果获取全权限账号
